name: pr-cleanup

on:
  pull_request:
    branches: [ main ]
    types: [ closed ]

permissions:
  contents: write

jobs:
  delete-unmerged-branch:
    if: ${{ github.event.pull_request.merged_at == '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf
        with:
          app-id: ${{ secrets.CLAUDE_APP_ID }}
          private-key: ${{ secrets.CLAUDE_PRIVATE_KEY }}

      - name: delete-unmerged-branch
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd
        with:
          github-token: ${{ steps.generate-token.outputs.token }}
          script: |
            const { repo, owner } = context.repo;
            const ref = `heads/${context.payload.pull_request.head.ref}`;
            const deleteParams = { owner, repo, ref };

            console.log(`Deleting branch: "${ref}"`);
            try {
              github.rest.git.deleteRef(deleteParams);
            } catch(e) {
              console.log("Cannot delete branch; error:", e);
            }
